"""Canonical constants for the P4 training and runtime contracts."""

from __future__ import annotations

from agent_ppo.feature import p2_contract
from agent_ppo.p4 import profiles as _profile_registry

RUN_NAME = "p4maze8h-closedloop-r3"
STAGE_NAME = "p4_nav_ppo"
STAGE_TYPE = "p4_nav_ppo"
TRAINING_HOURS = 8.0
TARGET_EFFECTIVE_SECONDS = 28_800.0
LEGACY_MAZE_TRAINING_HOURS = 2.0
LEGACY_MAZE_TARGET_EFFECTIVE_SECONDS = 7_200.0
DIAGNOSTIC_SECONDS = 0.0
PLATFORM_WALL_MARGIN_SECONDS = 900.0
PLATFORM_WALL_SECONDS = (
    TARGET_EFFECTIVE_SECONDS
    + DIAGNOSTIC_SECONDS
    + PLATFORM_WALL_MARGIN_SECONDS
)
PLATFORM_WALL_HOURS = PLATFORM_WALL_SECONDS / 3_600.0
SCHEDULE_BOUNDARIES_SECONDS = (1_800.0, 7_200.0, 21_600.0, 28_800.0)
LEGACY_MAZE_SCHEDULE_BOUNDARIES_SECONDS = (
    600.0, 1_800.0, 3_600.0, 5_400.0, 6_300.0, 7_200.0
)

LEGACY_ACTION_MAPPER_VERSION = "p2_legacy_action_mapper_v1"
ACTION_MAPPER_VERSION = "p4_capability_action_mapper_v1"
GOAL_BELIEF_VERSION = "p4_goal_belief_v4_full_track_metric_raw"
CAMERA_CONTRACT_VERSION = "p4_shared_camera_v4_recovery_nominal_light"
ADAPTER_RECORD_CONTRACT_VERSION = "p4_adapter_record_v1"
INSTANT_ADAPTER_RECORD_CONTRACT_VERSION = (
    "p4_adapter_record_v3_instant_command_inputfix"
)
SAFETY_REWARD_RAMP_VERSION = "p4_maze_credit_repair_safety_group_v1"
CHECKPOINT_CONTRACT_VERSION = "p4_maze_credit_repair_v1"
MAZE_CLOSED_LOOP_SAFETY_REWARD_VERSION = "p4_maze_closed_loop_recovery_translation_v4"
MAZE_CLOSED_LOOP_CHECKPOINT_VERSION = "p4_maze_closed_loop_v3"
INSTANT_COMMAND_REWARD_CONTRACT_VERSION = "p4_maze_instant_command_reward_r4"
INSTANT_COMMAND_CHECKPOINT_CONTRACT_VERSION = (
    "p4_maze_instant_command_r4_inputfix"
)
INSTANT_REPAIR_REWARD_CONTRACT_VERSION = (
    "p4_maze_reward_v5_instant_credit_repair"
)
INSTANT_REPAIR_CHECKPOINT_CONTRACT_VERSION = "p4_maze_instant_repair2h_v1"
INSTANT_COMMAND_STUCK_RESET_CONTRACT_VERSION = (
    "p4_stuck_reset_v6_instant_shadow_12s_to_active_10s"
)
INSTANT_COMMAND_PHASE_LABELS = (
    "instantwarm",
    "instantadapt",
    "instantcorrect",
    "instantstable",
    "instantfrozen",
)
INSTANT_REPAIR_PHASE_LABELS = (
    "repaircollect",
    "repairadapt",
    "repairtrain",
    "repairstable",
)
# Arena's checkpoint probe accepts only lowercase alphabetic stage labels.
# Keep the stable-direction schedule labels canonical here so the scheduler,
# checkpoint contract, and loader cannot silently diverge.
STABLE_DIRECTION_PHASE_LABELS = (
    "stablecalibrate",
    "stabledirection",
    "stablewarm",
    "stableearly",
    "stablemid",
    "stablelate",
    "stablestabilize",
)
INSTANT_REPAIR_SCHEDULE_BOUNDARIES_SECONDS = (300.0, 1_800.0, 5_400.0, 7_200.0)
INSTANT_REPAIR_CHECKPOINT_BOUNDARIES_SECONDS = (
    300.0,
    900.0,
    1_800.0,
    3_600.0,
    5_400.0,
    7_200.0,
)
INSTANT_COMMAND_SCHEDULE_BOUNDARIES_SECONDS = (
    1_800.0,
    7_200.0,
    10_800.0,
    12_600.0,
    28_800.0,
)
FULL_TRACK_CHECKPOINT_CONTRACT_VERSION = "p4_full_track_v2"
FULL_TRACK_REWARD_CONTRACT_VERSION = "p4_full_track_reward_v2_potential_straight"
FULL_TRACK_COMMAND_CONTRACT_VERSION = "p4_full_track_command_v2"
WORKER_WIRE_VERSION = "p4_worker_wire_v7_terminal_snapshot"
LEGACY_STUCK_RESET_CONTRACT_VERSION = "p4_stuck_reset_v3_sliding_window_10s"
STUCK_RESET_CONTRACT_VERSION = "p4_stuck_reset_v5_shadow_12s_to_active_10s"
LEGACY_ACTOR_MEAN_GUIDANCE_CONTRACT_VERSION = "p4_actor_mean_guidance_v1"
ACTOR_MEAN_GUIDANCE_CONTRACT_VERSION = "p4_actor_mean_guidance_v5_safe5_recovery_translation"
LEGACY_TRANSLATION_VECTOR_LIMITER_CONTRACT_VERSION = (
    "p4_translation_vector_limiter_v2_emergency_only"
)
TRANSLATION_VECTOR_LIMITER_CONTRACT_VERSION = "p4_translation_vector_limiter_v4_emergency_only"
LEGACY_NEAR_GOAL_CAPTURE_CONTRACT_VERSION = "p4_near_goal_capture_v1"
NEAR_GOAL_CAPTURE_CONTRACT_VERSION = "p4_near_goal_capture_v2_shadow_only"
STUCK_AUX_CONTRACT_VERSION = "p4_stuck_aux_v1"
# Training-only transport appended after the stable P3 493-column wire.
# These fields never enter either learned network and are absent from eval.
P4_WORKER_EXTRA_DIM = 26
P4_PRIVILEGED_WIRE_DIM = 519
RAW_GOAL_XY_SLICE = slice(0, 2)
STUCK_MOTION_CONFINED_INDEX = 2
STUCK_WALL_EVIDENCE_INDEX = 3
STUCK_CANDIDATE_INDEX = 4
STUCK_DURATION_S_INDEX = 5
STUCK_WOULD_RESET_INDEX = 6
STUCK_RESET_TRIGGERED_INDEX = 7
STUCK_MAPPING_VALID_INDEX = 8
STUCK_RESET_AFTER_PUSH_INDEX = 9
STUCK_SAVED_SECONDS_INDEX = 10
STUCK_COLLISION_TO_RESET_S_INDEX = 11
STUCK_TERM_AVAILABLE_INDEX = 12
STUCK_TERM_CONFIG_VALID_INDEX = 13
SPAWN_INSTALLED_INDEX = 14
STUCK_RAW_TERM_INDEX = 15
SPAWN_FULL_START_INDEX = 16
SPAWN_SEGMENT_INDEX = 17
SPAWN_QUARTILE_INDEX = 18
SPAWN_SAFE_POINT_INDEX = 19
SPAWN_REASON4_RETRY_COUNT_INDEX = 20
SPAWN_REASON4_EXHAUSTED_COUNT_INDEX = 21
SPAWN_REASON4_FALLBACK_APPLIED_COUNT_INDEX = 22
SPAWN_ALL_POSITION_APPLIED_COUNT_INDEX = 23
SPAWN_VALIDATION_FAILURE_COUNT_INDEX = 24
SPAWN_WRITE_FAILURE_COUNT_INDEX = 25

SOFT_CRUISE_MIN_VX = 0.60
SOFT_CRUISE_MAX_VX = 0.75
SOFT_CRUISE_LOW_WEIGHT = -0.03
SOFT_CRUISE_HIGH_WEIGHT = -0.02

P4_MAX_ABS_VY = 0.30
P4_MAX_ABS_WZ = 0.90
P4_MAX_VX = 1.00
P4_NAV_PERIOD_FRAMES = 5
P4_NAV_DT_S = p2_contract.CONTROL_DT_S * P4_NAV_PERIOD_FRAMES
# Actor85 was trained with the historical capability15 values below. Feeding
# the physical instant-command rates (10/6/18 per second) directly into those
# unnormalized LSTM inputs saturates the parent policy before PPO can adapt.
# Keep the parent observation semantics stable; the authoritative instant
# controller mode and physical rate are recorded separately in the command
# contract and never inferred from these compatibility slots.
INSTANT_ACTOR_CAPABILITY_PROFILE15 = (
    1.0, 1.0, 1.0,
    0.0, -0.30, -0.90,
    1.0, 0.30, 0.90,
    0.30, 0.30, 1.00,
    0.30, 0.60, 2.50,
)
INSTANT_CAPABILITY_CHANGE_RATE = (
    P4_MAX_VX / P4_NAV_DT_S,
    (2.0 * P4_MAX_ABS_VY) / P4_NAV_DT_S,
    (2.0 * P4_MAX_ABS_WZ) / P4_NAV_DT_S,
)
INSTANT_PARENT_ANCHOR_SLEW_UP = (0.30, 0.30, 1.00)
INSTANT_PARENT_ANCHOR_SLEW_RELEASE = (0.30, 0.60, 2.50)
P4_SLEW_RATE = (0.60, 0.60, 2.00)
P4_SLEW_RELEASE_RATE = (1.20, 1.20, 4.00)
LEGACY_P4_SLEW_RATE = (0.30, 0.40, 1.50)
LEGACY_P4_SLEW_RELEASE_RATE = (0.30, 0.80, 3.00)
STALE_GOAL_WAIT_MAX_ABS_VY = 0.10
STALE_GOAL_WAIT_MAX_ABS_WZ = 0.25

GOAL_NORMAL_D2 = 9.21
GOAL_CLIPPED_D2 = 25.0
GOAL_AGE_SLOW_START_S = 0.5
GOAL_AGE_SLOW_END_S = 2.0
GOAL_AGE_HOLD_END_S = 2.5
GOAL_FRESHNESS_FLOOR = 0.05
GOAL_PROCESS_SIGMA_V_M_S = 0.03
GOAL_PROCESS_SIGMA_WZ_RAD_S = 0.011
GOAL_REACQUIRE_SAMPLES = 5

STUCK_RESET_TERMINAL_PENALTY = -75.0
SUCCESS_IMPULSE = 200.0
FAILURE_IMPULSE = -60.0
TIMEOUT_IMPULSE = -40.0
LEGACY_STUCK_RESET_TERMINAL_PENALTY = -25.0
LEGACY_TIMEOUT_IMPULSE = -25.0
STUCK_SUSTAINED_GRACE_S = 0.8
STUCK_SUSTAINED_FULL_S = 2.0
STUCK_SUSTAINED_BASE = -0.010
STUCK_SUSTAINED_FLOOR = -0.05
LEGACY_STUCK_SUSTAINED_FLOOR = -0.02
P4_BODY_COLLISION_ONSET_BASE = -0.20
P4_BODY_COLLISION_ONSET_SEVERITY = -0.30
P4_BODY_COLLISION_PERSISTENT = -0.08
INSTANT_COMMAND_COLLISION_ONSET_BASE = -0.16
INSTANT_COMMAND_COLLISION_ONSET_SEVERITY = -0.24
INSTANT_COMMAND_COLLISION_PERSISTENT = -0.06
INSTANT_COMMAND_STUCK_SUSTAINED_GRACE_S = 0.8
INSTANT_COMMAND_STUCK_SUSTAINED_FULL_S = 2.0
INSTANT_COMMAND_STUCK_SUSTAINED_BASE = -0.010
INSTANT_COMMAND_STUCK_SUSTAINED_FLOOR = -0.04
INSTANT_REPAIR_COMMAND_RATE_WEIGHT = -0.003
INSTANT_REPAIR_TRACKING_ERROR_WEIGHT = -0.002
INSTANT_REPAIR_STALE_TRANSLATION_CAP_M_S = 0.20
INSTANT_REPAIR_STALE_YAW_CAP_RAD_S = 0.25
INSTANT_REPAIR_NEAR_GOAL_MAX_SPEED_M_S = 0.45
INSTANT_REPAIR_NEAR_GOAL_MIN_SPEED_M_S = 0.15
GOAL_SAFE_PREFERENCE_WEIGHT = -0.012
GOAL_SAFE_PREFERENCE_MARGIN = 0.08
GOAL_SAFE_PREFERENCE_SCALE = 0.35
ROUTE_EXCESS_WEIGHT = 0.0
ROUTE_EXCESS_CAP_M = 0.0
YAW_EXIT_RESPONSE_RAW_FLOOR = -0.006
TRANSLATION_LIMITER_RISK_THRESHOLD = 0.95
TRANSLATION_LIMITER_ALPHA_FLOOR = 0.75
TRANSLATION_LIMITER_RELEASE_PER_TICK = 0.20
LEGACY_TRANSLATION_LIMITER_RISK_THRESHOLD = 0.75
LEGACY_TRANSLATION_LIMITER_ALPHA_FLOOR = 0.60
NEAR_GOAL_CAPTURE_MIN_DISTANCE_M = 0.65
NEAR_GOAL_CAPTURE_MAX_DISTANCE_M = 1.20
NEAR_GOAL_CAPTURE_MIN_SPEED_M_S = 0.10
NEAR_GOAL_CAPTURE_GOAL_COSINE_MIN = 0.70
NEAR_GOAL_CAPTURE_FRESHNESS_MIN = 0.90
TEACHER_SAFE_MIN = 0.65
TEACHER_SAFE_MARGIN_MIN = 0.20
TEACHER_GOAL_SAFE_TIE_MARGIN = 0.10
TEACHER_GOAL_FRESHNESS_MIN = 0.75
TEACHER_DIRECTION_TOLERANCE_DEG = 35.0
TEACHER_EDGE_DIRECTION_TOLERANCE_DEG = 20.0
TEACHER_EDGE_SAFE_MIN = 0.65
TEACHER_EDGE_SPEED_CAP_MIN = 0.15
TEACHER_EDGE_SPEED_CAP_RANGE = 0.55
TEACHER_RECOVERY_MAX_VX = 0.12
TEACHER_RECOVERY_MIN_ABS_VY = 0.12
TEACHER_RECOVERY_SIDE_MARGIN = 0.10
TEACHER_SPEED_RISK_MIN = 0.90
TEACHER_MIN_VALID_STEPS = 64
TEACHER_SAFE5_ANGLES_DEG = (60.0, 30.0, 0.0, -30.0, -60.0)
TEACHER_SAFE5_HEIGHT_SECTORS = ((12, 16), (9, 14), (5, 11), (2, 7), (0, 4))
STUCK_RESET_DEFAULTS = {
    "enabled": True,
    "mode": "shadow",
    "schedule_enabled": False,
    "confirmation_s": 10.0,
    "initial_confirmation_s": 12.0,
    "activation_delay_s": 1_800.0,
    "tighten_after_s": 7_200.0,
    "resume_offset_s": 0.0,
    "radius_m": 0.50,
    "min_goal_distance_m": 0.80,
    "body_collision_force_n": 30.0,
    "wall_evidence_latch_s": 2.0,
    "episode_grace_s": 5.0,
    "push_grace_s": 2.0,
    "max_true_motion_speed_m_s": 0.08,
    "terminal_penalty": LEGACY_STUCK_RESET_TERMINAL_PENALTY,
}

FULL_TRACK_SEGMENT_LABELS = (
    "slope",
    "slope_inv",
    "stairs",
    "stairs_inv",
    "maze",
)
FULL_TRACK_SEGMENT_LENGTH_M = 8.0
SEGMENT_FRONTIER_WEIGHT = 1.0
MAZE_NEW_BEST_WEIGHT_PER_M = 1.0
MAZE_NEW_BEST_EPISODE_CAP = 6.0
LEGACY_MAZE_NEW_BEST_WEIGHT_PER_M = 2.0
LEGACY_MAZE_NEW_BEST_EPISODE_CAP = 12.0
OPEN_STRAIGHT_LATERAL_WEIGHT = -0.005
OPEN_STRAIGHT_S_TURN_WEIGHT = -0.005
OPEN_STRAIGHT_EXTRA_PATH_WEIGHT = -0.0025
OPEN_STRAIGHT_TOTAL_FLOOR = -0.0125
OPEN_STRAIGHT_TRUE_VY_DEADBAND_M_S = 0.08
OPEN_STRAIGHT_GOAL_BEARING_MAX_DEG = 15.0
OPEN_STRAIGHT_CENTER_SAFE_MIN = 0.75
OPEN_STRAIGHT_CENTER_BEST_MARGIN = 0.05
OPEN_STRAIGHT_BOUNDARY_MARGIN_M = 0.80

GOAL_JUMP_RATE_PER_S = 0.015
GOAL_JUMP_DURATION_S = (0.20, 0.80)
GOAL_JUMP_MIN_DISTANCE_M = 3.0
GOAL_JUMP_RADIAL_RANGE_M = (0.04, 0.20)
GOAL_JUMP_TANGENT_RANGE_M = (0.10, 1.00)

YAW_WINDOW_SECONDS = 1.0
RISK_RESPONSE_WINDOW_SECONDS = 1.0
# Global yaw cancellation is shadow-only. It previously penalized legitimate
# rapid obstacle-avoidance reversals without feeding the intervention state
# back into the policy.
YAW_EXEC_WEIGHT = 0.0
YAW_TRUE_WEIGHT = 0.0
YAW_TOTAL_FLOOR = 0.0
SAFETY_GROUP_FLOOR = -0.070
LEGACY_YAW_EXEC_WEIGHT = -0.012
LEGACY_YAW_TRUE_WEIGHT = -0.008
LEGACY_YAW_TOTAL_FLOOR = -0.020
LEGACY_SAFETY_GROUP_FLOOR = -0.060

PREDICTIVE_COLLISION_SCALE = 1.25
PREDICTIVE_RAW_FLOOR = -0.0300
MISSED_SAFE_RAW_FLOOR = -0.0400
SAFE_DIRECTION_GAP_SCALE = 0.35

NAVIGATION_ENCODER_LRS = {
    "conv1": 3.0e-6,
    "conv2": 1.0e-5,
    "conv3": 3.0e-5,
    "fc": 3.0e-5,
}
ACTOR_LR = 3.0e-4
CRITIC_LR = 3.0e-4
SAFETY_HEAD_LR = 3.0e-4
ADAPTER_LR = 1.0e-5

ADAPTER_COMPATIBILITY_REJECTION_REASONS = (
    "missing_contract",
    "mismatch_version",
    "mismatch_schema",
    "mismatch_low_level_digest",
    "mismatch_feedback_digest",
    "mismatch_capability_digest",
    "mismatch_response_capability_profile15",
    "mismatch_action_mapper",
    "mismatch_observation_layout",
    "mismatch_label_layout",
)

INSTANT_REPAIR_PROFILE = _profile_registry.DEFAULT_TRAIN_PROFILE
LEGACY_INSTANT_PROFILE = next(
    name
    for name in _profile_registry.LEGACY_PROFILE_NAMES
    if _profile_registry.get_training_profile(name).instant_command
)

__all__ = ('RUN_NAME', 'STAGE_NAME', 'STAGE_TYPE', 'TRAINING_HOURS', 'TARGET_EFFECTIVE_SECONDS', 'LEGACY_MAZE_TRAINING_HOURS', 'LEGACY_MAZE_TARGET_EFFECTIVE_SECONDS', 'DIAGNOSTIC_SECONDS', 'PLATFORM_WALL_MARGIN_SECONDS', 'PLATFORM_WALL_SECONDS', 'PLATFORM_WALL_HOURS', 'SCHEDULE_BOUNDARIES_SECONDS', 'LEGACY_MAZE_SCHEDULE_BOUNDARIES_SECONDS', 'LEGACY_ACTION_MAPPER_VERSION', 'ACTION_MAPPER_VERSION', 'GOAL_BELIEF_VERSION', 'CAMERA_CONTRACT_VERSION', 'ADAPTER_RECORD_CONTRACT_VERSION', 'INSTANT_ADAPTER_RECORD_CONTRACT_VERSION', 'SAFETY_REWARD_RAMP_VERSION', 'CHECKPOINT_CONTRACT_VERSION', 'MAZE_CLOSED_LOOP_SAFETY_REWARD_VERSION', 'MAZE_CLOSED_LOOP_CHECKPOINT_VERSION', 'INSTANT_COMMAND_REWARD_CONTRACT_VERSION', 'INSTANT_COMMAND_CHECKPOINT_CONTRACT_VERSION', 'INSTANT_REPAIR_REWARD_CONTRACT_VERSION', 'INSTANT_REPAIR_CHECKPOINT_CONTRACT_VERSION', 'INSTANT_COMMAND_STUCK_RESET_CONTRACT_VERSION', 'INSTANT_COMMAND_PHASE_LABELS', 'INSTANT_REPAIR_PHASE_LABELS', 'INSTANT_REPAIR_SCHEDULE_BOUNDARIES_SECONDS', 'INSTANT_REPAIR_CHECKPOINT_BOUNDARIES_SECONDS', 'INSTANT_COMMAND_SCHEDULE_BOUNDARIES_SECONDS', 'FULL_TRACK_CHECKPOINT_CONTRACT_VERSION', 'FULL_TRACK_REWARD_CONTRACT_VERSION', 'FULL_TRACK_COMMAND_CONTRACT_VERSION', 'WORKER_WIRE_VERSION', 'LEGACY_STUCK_RESET_CONTRACT_VERSION', 'STUCK_RESET_CONTRACT_VERSION', 'LEGACY_ACTOR_MEAN_GUIDANCE_CONTRACT_VERSION', 'ACTOR_MEAN_GUIDANCE_CONTRACT_VERSION', 'LEGACY_TRANSLATION_VECTOR_LIMITER_CONTRACT_VERSION', 'TRANSLATION_VECTOR_LIMITER_CONTRACT_VERSION', 'LEGACY_NEAR_GOAL_CAPTURE_CONTRACT_VERSION', 'NEAR_GOAL_CAPTURE_CONTRACT_VERSION', 'STUCK_AUX_CONTRACT_VERSION', 'P4_WORKER_EXTRA_DIM', 'P4_PRIVILEGED_WIRE_DIM', 'RAW_GOAL_XY_SLICE', 'STUCK_MOTION_CONFINED_INDEX', 'STUCK_WALL_EVIDENCE_INDEX', 'STUCK_CANDIDATE_INDEX', 'STUCK_DURATION_S_INDEX', 'STUCK_WOULD_RESET_INDEX', 'STUCK_RESET_TRIGGERED_INDEX', 'STUCK_MAPPING_VALID_INDEX', 'STUCK_RESET_AFTER_PUSH_INDEX', 'STUCK_SAVED_SECONDS_INDEX', 'STUCK_COLLISION_TO_RESET_S_INDEX', 'STUCK_TERM_AVAILABLE_INDEX', 'STUCK_TERM_CONFIG_VALID_INDEX', 'SPAWN_INSTALLED_INDEX', 'STUCK_RAW_TERM_INDEX', 'SPAWN_FULL_START_INDEX', 'SPAWN_SEGMENT_INDEX', 'SPAWN_QUARTILE_INDEX', 'SPAWN_SAFE_POINT_INDEX', 'SPAWN_REASON4_RETRY_COUNT_INDEX', 'SPAWN_REASON4_EXHAUSTED_COUNT_INDEX', 'SPAWN_REASON4_FALLBACK_APPLIED_COUNT_INDEX', 'SPAWN_ALL_POSITION_APPLIED_COUNT_INDEX', 'SPAWN_VALIDATION_FAILURE_COUNT_INDEX', 'SPAWN_WRITE_FAILURE_COUNT_INDEX', 'SOFT_CRUISE_MIN_VX', 'SOFT_CRUISE_MAX_VX', 'SOFT_CRUISE_LOW_WEIGHT', 'SOFT_CRUISE_HIGH_WEIGHT', 'P4_MAX_ABS_VY', 'P4_MAX_ABS_WZ', 'P4_MAX_VX', 'P4_NAV_PERIOD_FRAMES', 'P4_NAV_DT_S', 'INSTANT_ACTOR_CAPABILITY_PROFILE15', 'INSTANT_CAPABILITY_CHANGE_RATE', 'INSTANT_PARENT_ANCHOR_SLEW_UP', 'INSTANT_PARENT_ANCHOR_SLEW_RELEASE', 'P4_SLEW_RATE', 'P4_SLEW_RELEASE_RATE', 'LEGACY_P4_SLEW_RATE', 'LEGACY_P4_SLEW_RELEASE_RATE', 'STALE_GOAL_WAIT_MAX_ABS_VY', 'STALE_GOAL_WAIT_MAX_ABS_WZ', 'GOAL_NORMAL_D2', 'GOAL_CLIPPED_D2', 'GOAL_AGE_SLOW_START_S', 'GOAL_AGE_SLOW_END_S', 'GOAL_AGE_HOLD_END_S', 'GOAL_FRESHNESS_FLOOR', 'GOAL_PROCESS_SIGMA_V_M_S', 'GOAL_PROCESS_SIGMA_WZ_RAD_S', 'GOAL_REACQUIRE_SAMPLES', 'STUCK_RESET_TERMINAL_PENALTY', 'SUCCESS_IMPULSE', 'FAILURE_IMPULSE', 'TIMEOUT_IMPULSE', 'LEGACY_STUCK_RESET_TERMINAL_PENALTY', 'LEGACY_TIMEOUT_IMPULSE', 'STUCK_SUSTAINED_GRACE_S', 'STUCK_SUSTAINED_FULL_S', 'STUCK_SUSTAINED_BASE', 'STUCK_SUSTAINED_FLOOR', 'LEGACY_STUCK_SUSTAINED_FLOOR', 'P4_BODY_COLLISION_ONSET_BASE', 'P4_BODY_COLLISION_ONSET_SEVERITY', 'P4_BODY_COLLISION_PERSISTENT', 'INSTANT_COMMAND_COLLISION_ONSET_BASE', 'INSTANT_COMMAND_COLLISION_ONSET_SEVERITY', 'INSTANT_COMMAND_COLLISION_PERSISTENT', 'INSTANT_COMMAND_STUCK_SUSTAINED_GRACE_S', 'INSTANT_COMMAND_STUCK_SUSTAINED_FULL_S', 'INSTANT_COMMAND_STUCK_SUSTAINED_BASE', 'INSTANT_COMMAND_STUCK_SUSTAINED_FLOOR', 'INSTANT_REPAIR_COMMAND_RATE_WEIGHT', 'INSTANT_REPAIR_TRACKING_ERROR_WEIGHT', 'INSTANT_REPAIR_STALE_TRANSLATION_CAP_M_S', 'INSTANT_REPAIR_STALE_YAW_CAP_RAD_S', 'INSTANT_REPAIR_NEAR_GOAL_MAX_SPEED_M_S', 'INSTANT_REPAIR_NEAR_GOAL_MIN_SPEED_M_S', 'GOAL_SAFE_PREFERENCE_WEIGHT', 'GOAL_SAFE_PREFERENCE_MARGIN', 'GOAL_SAFE_PREFERENCE_SCALE', 'ROUTE_EXCESS_WEIGHT', 'ROUTE_EXCESS_CAP_M', 'YAW_EXIT_RESPONSE_RAW_FLOOR', 'TRANSLATION_LIMITER_RISK_THRESHOLD', 'TRANSLATION_LIMITER_ALPHA_FLOOR', 'TRANSLATION_LIMITER_RELEASE_PER_TICK', 'LEGACY_TRANSLATION_LIMITER_RISK_THRESHOLD', 'LEGACY_TRANSLATION_LIMITER_ALPHA_FLOOR', 'NEAR_GOAL_CAPTURE_MIN_DISTANCE_M', 'NEAR_GOAL_CAPTURE_MAX_DISTANCE_M', 'NEAR_GOAL_CAPTURE_MIN_SPEED_M_S', 'NEAR_GOAL_CAPTURE_GOAL_COSINE_MIN', 'NEAR_GOAL_CAPTURE_FRESHNESS_MIN', 'TEACHER_SAFE_MIN', 'TEACHER_SAFE_MARGIN_MIN', 'TEACHER_GOAL_SAFE_TIE_MARGIN', 'TEACHER_GOAL_FRESHNESS_MIN', 'TEACHER_DIRECTION_TOLERANCE_DEG', 'TEACHER_EDGE_DIRECTION_TOLERANCE_DEG', 'TEACHER_EDGE_SAFE_MIN', 'TEACHER_EDGE_SPEED_CAP_MIN', 'TEACHER_EDGE_SPEED_CAP_RANGE', 'TEACHER_RECOVERY_MAX_VX', 'TEACHER_RECOVERY_MIN_ABS_VY', 'TEACHER_RECOVERY_SIDE_MARGIN', 'TEACHER_SPEED_RISK_MIN', 'TEACHER_MIN_VALID_STEPS', 'TEACHER_SAFE5_ANGLES_DEG', 'TEACHER_SAFE5_HEIGHT_SECTORS', 'STUCK_RESET_DEFAULTS', 'FULL_TRACK_SEGMENT_LABELS', 'FULL_TRACK_SEGMENT_LENGTH_M', 'SEGMENT_FRONTIER_WEIGHT', 'MAZE_NEW_BEST_WEIGHT_PER_M', 'MAZE_NEW_BEST_EPISODE_CAP', 'LEGACY_MAZE_NEW_BEST_WEIGHT_PER_M', 'LEGACY_MAZE_NEW_BEST_EPISODE_CAP', 'OPEN_STRAIGHT_LATERAL_WEIGHT', 'OPEN_STRAIGHT_S_TURN_WEIGHT', 'OPEN_STRAIGHT_EXTRA_PATH_WEIGHT', 'OPEN_STRAIGHT_TOTAL_FLOOR', 'OPEN_STRAIGHT_TRUE_VY_DEADBAND_M_S', 'OPEN_STRAIGHT_GOAL_BEARING_MAX_DEG', 'OPEN_STRAIGHT_CENTER_SAFE_MIN', 'OPEN_STRAIGHT_CENTER_BEST_MARGIN', 'OPEN_STRAIGHT_BOUNDARY_MARGIN_M', 'GOAL_JUMP_RATE_PER_S', 'GOAL_JUMP_DURATION_S', 'GOAL_JUMP_MIN_DISTANCE_M', 'GOAL_JUMP_RADIAL_RANGE_M', 'GOAL_JUMP_TANGENT_RANGE_M', 'YAW_WINDOW_SECONDS', 'RISK_RESPONSE_WINDOW_SECONDS', 'YAW_EXEC_WEIGHT', 'YAW_TRUE_WEIGHT', 'YAW_TOTAL_FLOOR', 'SAFETY_GROUP_FLOOR', 'LEGACY_YAW_EXEC_WEIGHT', 'LEGACY_YAW_TRUE_WEIGHT', 'LEGACY_YAW_TOTAL_FLOOR', 'LEGACY_SAFETY_GROUP_FLOOR', 'PREDICTIVE_COLLISION_SCALE', 'PREDICTIVE_RAW_FLOOR', 'MISSED_SAFE_RAW_FLOOR', 'SAFE_DIRECTION_GAP_SCALE', 'NAVIGATION_ENCODER_LRS', 'ACTOR_LR', 'CRITIC_LR', 'SAFETY_HEAD_LR', 'ADAPTER_LR', 'ADAPTER_COMPATIBILITY_REJECTION_REASONS', 'INSTANT_REPAIR_PROFILE', 'LEGACY_INSTANT_PROFILE')
