#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
"""Compact R1 Standard PPO monitoring panels."""

from kaiwudrl.common.monitor.monitor_config_builder import MonitorConfigBuilder


def build_monitor():
    """Build panels whose display and metric names stay within 20 characters."""
    monitor = MonitorConfigBuilder()
    return (
        monitor.title("Standard_PPO")
        .add_group(group_name="训练", group_name_en="train")
        .add_panel(name="回合步数", name_en="ep_steps", type="line")
            .add_metric(metrics_name="ep_steps", expr="avg(ep_steps{})")
            .end_panel()
        .add_panel(name="回合奖励", name_en="ep_reward", type="line")
            .add_metric(metrics_name="ep_reward", expr="avg(ep_reward{})")
            .end_panel()
        .add_panel(name="回合数", name_en="ep_count", type="line")
            .add_metric(metrics_name="ep_count", expr="max(ep_count{})")
            .end_panel()
        .end_group()

        .add_group(group_name="优化", group_name_en="ppo_opt")
        .add_panel(name="总损失", name_en="total_loss", type="line")
            .add_metric(metrics_name="total_loss", expr="avg(total_loss{})")
            .end_panel()
        .add_panel(name="策略损失", name_en="policy_loss", type="line")
            .add_metric(metrics_name="policy_loss", expr="avg(policy_loss{})")
            .end_panel()
        .add_panel(name="价值损失", name_en="value_loss", type="line")
            .add_metric(metrics_name="value_loss", expr="avg(value_loss{})")
            .end_panel()
        .add_panel(name="熵损失", name_en="entropy_loss", type="line")
            .add_metric(metrics_name="entropy_loss", expr="avg(entropy_loss{})")
            .end_panel()
        .add_panel(name="学习率", name_en="learning_rate", type="line")
            .add_metric(metrics_name="learning_rate", expr="avg(learning_rate{})")
            .end_panel()
        .end_group()

        .add_group(group_name="速度", group_name_en="speed")
        .add_panel(name="速度课程", name_en="vel_stage", type="line")
            .add_metric(metrics_name="vel_stage", expr="avg(vel_stage{})")
            .end_panel()
        .add_panel(name="速度追踪", name_en="vel_track", type="line")
            .add_metric(metrics_name="vel_track", expr="avg(vel_track{})")
            .end_panel()
        .add_panel(name="速度上限", name_en="vel_max", type="line")
            .add_metric(metrics_name="vel_max", expr="avg(vel_max{})")
            .end_panel()
        .add_panel(name="前向奖励", name_en="rew_vx", type="line")
            .add_metric(metrics_name="rew_vx", expr="avg(rew_vx{})")
            .end_panel()
        .add_panel(name="偏航奖励", name_en="rew_yaw", type="line")
            .add_metric(metrics_name="rew_yaw", expr="avg(rew_yaw{})")
            .end_panel()
        .add_panel(name="速度对照", name_en="vx_stat", type="stat")
            .add_metric(metrics_name="vx_cmd", expr="avg(vx_cmd{})")
            .add_metric(metrics_name="vx_real", expr="avg(vx_real{})")
            .end_panel()
        .add_panel(name="速度误差", name_en="vx_err", type="line")
            .add_metric(metrics_name="vx_err", expr="avg(vx_err{})")
            .end_panel()
        .end_group()

        .add_group(group_name="地形", group_name_en="terrain")
        .add_panel(name="地形难度", name_en="ter_level", type="line")
            .add_metric(metrics_name="ter_level", expr="avg(ter_level{})")
            .end_panel()
        .add_panel(name="地形范围", name_en="ter_range", type="stat")
            .add_metric(metrics_name="ter_min", expr="avg(ter_min{})")
            .add_metric(metrics_name="ter_max", expr="avg(ter_max{})")
            .end_panel()
        .add_panel(name="地形切换", name_en="ter_switch", type="stat")
            .add_metric(metrics_name="ter_up", expr="avg(ter_up{})")
            .add_metric(metrics_name="ter_down", expr="avg(ter_down{})")
            .end_panel()
        .end_group()

        .add_group(group_name="稳定", group_name_en="stability")
        .add_panel(name="姿态奖励", name_en="rew_flat", type="line")
            .add_metric(metrics_name="rew_flat", expr="avg(rew_flat{})")
            .end_panel()
        .add_panel(name="接触惩罚", name_en="rew_contact", type="line")
            .add_metric(metrics_name="rew_contact", expr="avg(rew_contact{})")
            .end_panel()
        .add_panel(name="终止惩罚", name_en="rew_term", type="line")
            .add_metric(metrics_name="rew_term", expr="avg(rew_term{})")
            .end_panel()
        .add_panel(name="机身高度", name_en="body_h", type="line")
            .add_metric(metrics_name="body_h", expr="avg(body_h{})")
            .end_panel()
        .add_panel(name="倾斜速度", name_en="tilt_rate", type="line")
            .add_metric(metrics_name="tilt_rate", expr="avg(tilt_rate{})")
            .end_panel()
        .add_panel(name="动态倾斜风险", name_en="reward_dynamic_tilt_risk", type="line")
            .add_metric(
                metrics_name="reward_dynamic_tilt_risk",
                expr="avg(reward_dynamic_tilt_risk{})",
            )
            .end_panel()
        .end_group()

        .add_group(group_name="能耗动作", group_name_en="energy_act")
        .add_panel(name="能耗惩罚", name_en="rew_energy", type="line")
            .add_metric(metrics_name="rew_energy", expr="avg(rew_energy{})")
            .end_panel()
        .add_panel(name="扭矩惩罚", name_en="rew_torque", type="line")
            .add_metric(metrics_name="rew_torque", expr="avg(rew_torque{})")
            .end_panel()
        .add_panel(name="动作惩罚", name_en="rew_action", type="line")
            .add_metric(metrics_name="rew_action", expr="avg(rew_action{})")
            .end_panel()
        .build()
    )
